# adapted from https://gist.github.com/dan-blanchard/7045057
language: python
python:
  - 2.7
  - 3.5
notifications:
  email: false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH="$HOME/miniconda2/bin:$PATH"
  - hash -r
  - pwd
  - ls ~/
  - ls ~/miniconda2/bin
  - conda update --yes conda

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose
  - pip install quantities python-coveralls nose-cov
  - python setup.py install

# Run test
script:
  - nosetests --with-coverage
